"$schema" = 'https://starship.rs/config-schema.json'
# 
format = """
[╭─](fg:light bg:none)\
[](fg:darkest bg:none)\
${custom.home}\
[](fg:darkest bg:dark)\
$directory\
[ ](fg:dark bg:medium)\
$nodejs\
$lua\
$rust\
$golang\
$pulumi\
$azure\
[](fg:medium bg:none)\
$fill\
$status\
$cmd_duration\
$time\
\n\
[╰─](fg:light bg:none)\
$character\
 """

palette = "purple"

[palettes.purple]
darkest = "#8a44ff" 
dark    = "#9c61ff"
medium  = "#af7dff"
light   = "#d0bfff"
text = "#efefff"
text2 = "#8a44ff"

[fill]
symbol = '-'
style = 'light dimmed'

[custom.home]
style = "fg:text bg:darkest"
command = "$HOME/.config/zsh/functions/get_icon"
format = '[ $output ]($style)'
when = true

[directory]
style = "fg:text bg:dark"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:text bg:medium"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:medium"
format = '[$all_status ]($style)'
untracked = '[+${count}](bold fg:#ffccf0 bg:medium)'
modified = '[~${count}](bold fg:#e5dbff bg:medium)'
deleted = '[-${count}](bold fg:#ff9999 bg:medium)'
conflicted = '[!${count}](bold fg:#ff6666 bg:medium)'
staged = '[✓${count}](bold fg:#99ff99 bg:medium)'

[nodejs]
symbol = " "
style = "fg:#6E9E58 bg:medium"
format = '[$symbol$version ]($style)'

[lua]
symbol = "󰢱 "
style = "fg:blue bg:medium"
format = '[$symbol$version ]($style)'

[rust]
symbol = " "
style = "fg:red bg:medium"
format = '[$symbol$version ]($style)'

[golang]
symbol = " "
style = "fg:text2 bg:medium"
format = '[$symbol$version ]($style)'

[pulumi]
symbol = " "
style = "fg:#E27680 bg:medium"
format = '[$symbol$stack ]($style)'

[azure]
disabled = false
format = '[$symbol($subscription) ]($style)'
symbol = '󰠅 '
style = "fg:blue bg:medium"

[status]
disabled = false
style = 'fg:#ff6699 bg:none'
format = '[ $common_meaning$signal_name\($int$signal_number\)]($style) '

[cmd_duration]
min_time = 1
style = "fg:dark bg:none"
format = '[ 󱦟 $duration]($style)'

[time]
disabled = false
time_format = "%H:%M:%S"
style="fg:dark bg:none"
format = '[   $time ]($style)'

[character]
success_symbol = '[>](fg:light)'
error_symbol = '[×](bold fg:#ff49a0)'
format = '$symbol '

